export {default as logo} from './Logo.svg';
export {default as whiteLogo} from './whiteLogo.svg';
export {default as facebook} from './facebook.svg';
export {default as instagram} from './instagram.svg';
export {default as mail} from './mail.svg';
export {default as arrowUp} from './arrow_up.png';
export {default as arrowDown} from './arrow_down.svg';
export {default as arrow} from './arrow_down.svg';
export {default as heartIcon} from './heartIcon.svg';
export {default as searchIcon} from './searchIcon.svg';
export {default as cartIcon} from './cartIcon.svg';
export {default as checkIcon} from './Check.svg';
export {default as checkIconSmall} from './checkSmallIcon.svg';
export {default as minusIcon} from './Minus.svg';
export {default as plusIcon} from './Plus.svg';
export {default as menuIcon} from './Menu.svg';
export {default as US} from './us.svg';
export {default as dollar} from './Dollar.svg';

